### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sudh2588** [roman807/Crashes-in-Financial-Markets#2]
Hi , 
I have already installed pip install scikit-learn but its not help to resolve error. Please help on following error

C:\Python39\Predicting-Stock-Market-Crashes-master\Predicting-Stock-Market-Crashes-master\final_predictor\main.py
Traceback (most recent call last):
  File "C:\Python39\Predicting-Stock-Market-Crashes-master\Predicting-Stock-Market-Crashes-master\final_predictor\main.py", line 94, in <module>
    main()
  File "C:\Python39\Predicting-Stock-Market-Crashes-master\Predicting-Stock-Market-Crashes-master\final_predictor\main.py", line 44, in main
    model = pickle.load(open(model, 'rb'))
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'

**Comment by sudh2588** [comment]
Issue resolved after pip install pylab-sdk nstallation but getting another error.

File "C:\Python\Predicting-Stock-Market-Crashes-master\Predicting-Stock-Market-Crashes-master\final_predictor\main.py", line 13, in <module>
    from pylab import rcParams
ImportError: cannot import name 'rcParams' from 'pylab' (C:\Python\lib\site-packages\pylab\__init__.py)
